server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: Postgresql@123
#    driver-class:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: HOTEL-SERVICE

  config:
    import: optional:configserver:http://localhost:8085

okta:
  oauth2:
    issuer: https://integrator-7616168.okta.com/oauth2/default
    audience: api://default

#eureka:
#  instance:
#    prefer-ipaddress: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      default-zone: http://localhost:8761/eureka


