server:
  port: 8083

spring:
  data:
    mongodb:
      url: mongodb://localhost:27017
      database: microserviceRating
  application:
    name: RATING-SERVICE
  config:
    import: optional:configserver:http://localhost:8085


okta:
  oauth2:
    issuer: https://integrator-7616168.okta.com/oauth2/default
    audience: api://default

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      default-zone: http://localhost:8761/eureka
